# deploy-nixpacks.toml
# This configures Nixpacks for Railway deployment

[phases.setup]
nixPkgs = [
  "nodejs_18",
  "python39",
  "python39Packages.pip", 
  "python39Packages.setuptools",
  "python39Packages.wheel",
  "unixODBC",
  "unixODBCDrivers.msodbcsql17",
  "curl",
  "gnused",
  "gcc"
]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install && cd ..",
  "cd frontend/backend && npm install && cd ../..",
  "pip install --upgrade pip",
  "pip install -r frontend/backend/requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build --output-path=../dist_railway && cd .."
]
output = "dist_railway"

[phases.setup.env]
PYTHONUNBUFFERED = "1"

[phases.release]
cmds = [
  "echo 'Release phase completed'"
]

[start]
cmd = "node railway-up.js"

[processes]
web = "cd $PROJECT_DIR && node railway-up.js"
api = "cd $PROJECT_DIR/frontend/backend && python Repository.py"
worker = "cd $PROJECT_DIR/frontend/backend && node server.js"

