version: '3.8'

services:  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mpp-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Express
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - app-network  flask-backend:
    build:
      context: ./frontend/backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ./frontend/backend/uploads:/app/uploads
      - ./certs:/app/certs
    ports:
      - "443:5000"
    environment:
      - FLASK_ENV=production
      - SQL_SERVER_CONNECTION_STRING=mssql+pyodbc://sa:StrongPassword123!@database:1433/MusicLibrary?driver=ODBC+Driver+17+for+SQL+Server
      - SSL_CERT=./certs/certificate.crt
      - SSL_KEY=./certs/private.key
    depends_on:
      - database
    networks:
      - app-network  node-backend:
    build:
      context: ./frontend/backend
      dockerfile: Dockerfile.node
    container_name: node-backend
    volumes:
      - ./frontend/backend/uploads:/app/uploads
      - ./certs:/app/certs
    ports:
      - "3443:3000"
    environment:
      - NODE_ENV=production
      - SQL_SERVER_CONNECTION_STRING=mssql://sa:StrongPassword123!@database:1433/MusicLibrary
      - SSL_CERT=./certs/certificate.crt
      - SSL_KEY=./certs/private.key
    depends_on:
      - database
      - flask-backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - node-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 