version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mpp-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - app-network

  flask-backend:
    build:
      context: ./frontend/backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ./frontend/backend/uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - SQL_SERVER_CONNECTION_STRING=mssql+pyodbc://sa:${SQL_SERVER_PASSWORD}@database:1433/MusicLibrary?driver=ODBC+Driver+17+for+SQL+Server
    depends_on:
      - database
    networks:
      - app-network

  node-backend:
    build:
      context: ./frontend/backend
      dockerfile: Dockerfile.node
    container_name: node-backend
    volumes:
      - ./frontend/backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - SQL_SERVER_CONNECTION_STRING=mssql://sa:${SQL_SERVER_PASSWORD}@database:1433/MusicLibrary
    depends_on:
      - database
      - flask-backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.https
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - node-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
