[build]
nixpkgsFile = "nixpkgs.json"

[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip", "unixODBC", "curl"]

[phases.install]
cmds = [
  "cd frontend/backend && pip install -r requirements.txt",
  "cd frontend/backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "npm start"

[processes]
web = "npm run web"
worker = "npm run worker"
